### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by darreniyer0601**
Components:
- shifted all forms to a Forms folder
- updated forms by clearing up unnecessary code
- replaced custom checks with bootstrap validation (except where required)
- renamed AnnLabel to AnnouncementLabel

Context:
- replaced fetch with axios for making requests
- removed ApplicationContext 
- added UserContext to handle user related routes

Pages:
- updated all auth pages in the auth sub-folder
- updated import statements in announcements.tsx

Styles:
- cleaned up forms.module.css
- renamed ann.module.css to announcements.module.css
- removed unnecessary styling classes from announcements.module.css

Package.json:
- added proxy to localhost:5000 for testing
- installed axios for making api calls

### CODE REVIEW

**Comment by rhythm1705** [comment]
Are the api calls working fine now?

**Comment by darreniyer0601** [comment]
> Are the api calls working fine now?

Unfortunately not.. Requests aren't getting proxied to 5000 despite the proxy in package.json, for some reason, so it's not making the calls properly. But it shouldn't cause any render problems since errors are being handled without any issues.

**Comment by rhythm1705** [comment]
I see. I will work on that tomorrow and see what is causing the problem.

**Comment by rhythm1705** [comment]
https://medium.com/bb-tutorials-and-thoughts/next-js-how-to-proxy-to-backend-server-987174737331
I found the reason. I'll try adding this to backend to see if it works.

**Comment by darreniyer0601** [comment]
> https://medium.com/bb-tutorials-and-thoughts/next-js-how-to-proxy-to-backend-server-987174737331
> I found the reason. I'll try adding this to backend to see if it works.

Sounds good.

**Pull request merged**
